project_id = "apkprahhodaxildwznzy"

[functions.ai-script]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.trigger-generation]
verify_jwt = false

[functions.update-scene]
verify_jwt = false

[functions.audio-splitter]
verify_jwt = false

[functions.video-stitcher]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
